name: morsetest2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  supabase_flutter: ^2.3.4
  shared_preferences: ^2.0.7
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.1
  vibration : ^1.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
